version: "3.3"

networks:
  postgres-network:
    driver: bridge

services:
  api:
    build: .
    ports:
      - "8080:8080"
    restart: always
    networks:
      - postgres-network
  pg:
    ports:
      - 5432:5432
    image: postgres
    restart: always
    networks:
      - postgres-network
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: atlas

  adminer:
    image: adminer:latest
    ports:
      - 8087:8080
    networks:
      - postgres-network
