name: Build and Deploy to Docker Hub

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_IMAGE: mnaeem99/atlas_app_backend  # Set this to your Docker Hub repository name

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: gradle wrapper

      - run: ./gradlew bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Navigate to the workspace directory where the code is checked out
          cd $GITHUB_WORKSPACE
          # Build and tag the Docker image
          docker build -t ${{ env.DOCKER_IMAGE }}:latest -t ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} .
          # Push the Docker image to Docker Hub
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_IMAGE }}:latest
          echo "image=${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
